import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/admin/logs',
    name: 'admin.logs',
    component: () => import('@/modules/admin/pages/AuditLogsPage.vue'),
    meta: { requiresAuth: true, roles: ['admin', 'auditor'], title: 'Logs de Auditoria', module: 'admin.logs' },
  },
  {
    path: '/',
    name: 'dashboard',
    component: () => import('@/modules/dashboard/pages/DashboardPage.vue'),
    meta: { requiresAuth: true, title: 'Dashboard', module: 'dashboard' },
  },
  {
    path: '/login',
    name: 'login',
    component: () => import('@/views/auth/LoginView.vue'),
    meta: { guest: true, title: 'Login' },
  },
  {
    path: '/register',
    name: 'register',
    component: () => import('@/views/auth/RegisterView.vue'),
    meta: { guest: true, title: 'Cadastro' },
  },
  {
    path: '/forgot-password',
    name: 'forgot-password',
    component: () => import('@/views/auth/ForgotPasswordView.vue'),
    meta: { guest: true, title: 'Recuperar Senha' },
  },
  {
    path: '/reset-password',
    name: 'reset-password',
    component: () => import('@/views/auth/ResetPasswordView.vue'),
    meta: { guest: true, title: 'Redefinir Senha' },
  },
  {
    path: '/verify-email/:id?/:hash?',
    name: 'verify-email',
    component: () => import('@/views/auth/VerifyEmailView.vue'),
    meta: { guest: true, title: 'Verificar Email' },
  },
  {
    path: '/verify-email',
    name: 'verify-email.pending',
    component: () => import('@/views/auth/VerifyEmailPendingView.vue'),
    meta: { guest: true, title: 'Verificar Email' },
  },
  {
    path: '/admin/users',
    name: 'admin.users',
    component: () => import('@/modules/admin/pages/UsersPage.vue'),
    meta: { requiresAuth: true, roles: ['admin', 'supervisor'], title: 'Usuários', module: 'admin.users' },
  },
  {
    path: '/admin/roles',
    name: 'admin.roles',
    component: () => import('@/modules/admin/pages/RolesPage.vue'),
    meta: { requiresAuth: true, roles: ['admin'], title: 'Perfis de Acesso', module: 'admin.roles' },
  },
  {
    path: '/profile',
    name: 'profile',
    component: () => import('@/modules/profile/pages/ProfilePage.vue'),
    meta: {
      requiresAuth: true,
      title: 'Meu Perfil',
      module: 'profile',
    },
  },
  {
    path: '/equipments',
    name: 'equipments',
    component: () => import('@/modules/equipment/pages/EquipmentListPage.vue'),
    meta: { requiresAuth: true, module: 'gestao', title: 'Equipamentos' },
  },
  {
    path: '/equipments/new',
    name: 'equipment-create',
    component: () => import('@/modules/equipment/pages/EquipmentFormPage.vue'),
    meta: { requiresAuth: true, module: 'gestao', title: 'Novo Equipamento' },
  },
  {
    path: '/equipments/:id/edit',
    name: 'equipment-edit',
    component: () => import('@/modules/equipment/pages/EquipmentFormPage.vue'),
    meta: { requiresAuth: true, module: 'gestao', title: 'Editar Equipamento' },
  },
  {
    path: '/equipments/:id',
    name: 'equipment-detail',
    component: () => import('@/modules/equipment/pages/EquipmentDetailPage.vue'),
    meta: { requiresAuth: true, module: 'gestao', title: 'Detalhes do Equipamento' },
  },
  {
    path: '/inventory',
    name: 'inventory.index',
    component: () => import('@/modules/inventory/pages/InventoryItemListPage.vue'),
    meta: { requiresAuth: true, module: 'inventory.index', title: 'Estoque' },
  },
  {
    path: '/inventory/new',
    name: 'inventory.create',
    component: () => import('@/modules/inventory/pages/InventoryItemFormPage.vue'),
    meta: { requiresAuth: true, module: 'inventory.index', title: 'Novo Item' },
  },
  {
    path: '/inventory/:id/edit',
    name: 'inventory.edit',
    component: () => import('@/modules/inventory/pages/InventoryItemFormPage.vue'),
    meta: { requiresAuth: true, module: 'inventory.index', title: 'Editar Item' },
  },
  {
    path: '/inventory/:id',
    name: 'inventory.show',
    component: () => import('@/modules/inventory/pages/InventoryItemDetailPage.vue'),
    meta: { requiresAuth: true, module: 'inventory.index', title: 'Detalhes do Item' },
  },
  {
    path: '/movements',
    name: 'movements.index',
    component: () => import('@/modules/inventory/pages/InventoryMovementsPage.vue'),
    meta: { requiresAuth: true, module: 'movements.index', title: 'Movimentações' },
  },
  {
    path: '/loans',
    name: 'loans.index',
    component: () => import('@/views/PlaceholderPage.vue'),
    meta: { requiresAuth: true, module: 'loans.index', title: 'Empréstimos' },
  },
  {
    path: '/calibrations',
    name: 'calibrations.index',
    component: () => import('@/views/PlaceholderPage.vue'),
    meta: { requiresAuth: true, module: 'calibrations.index', title: 'Calibrações' },
  },
  {
    path: '/verifications',
    name: 'verifications.index',
    component: () => import('@/views/PlaceholderPage.vue'),
    meta: { requiresAuth: true, module: 'verifications.index', title: 'Aferições' },
  },
  {
    path: '/maintenance',
    name: 'maintenance.index',
    component: () => import('@/views/PlaceholderPage.vue'),
    meta: { requiresAuth: true, module: 'maintenance.index', title: 'Manutenções' },
  },
  {
    path: '/reports',
    name: 'reports.index',
    component: () => import('@/views/PlaceholderPage.vue'),
    meta: { requiresAuth: true, module: 'reports.index', title: 'Relatórios' },
  },
  {
    path: '/unauthorized',
    name: 'unauthorized',
    component: () => import('@/views/UnauthorizedView.vue'),
    meta: { requiresAuth: true, title: 'Acesso Negado' },
  },
]
